all:dulassociaterq.o dulassociateac.o dulcfindrq.o dulcfindrsp.o

dulassociaterq.o: dulassociaterq.h dulassociaterq.cpp
	g++ -g -c dulassociaterq.cpp
dulassociateac.o: dulassociateac.h dulassociateac.cpp
	g++ -g -c dulassociateac.cpp
dulcfindrq.o: dulcfindrq.h dulcfindrq.cpp
	g++ -g -c dulcfindrq.cpp
dulcfindrsp.o: dulcfindrsp.h dulcfindrsp.cpp
	g++ -g -c dulcfindrsp.cpp
clean:
	rm *.o