all:dulassociaterq.o dulassociateac.o dulpdatatfrq.o dulcfindrsp.o

dulassociaterq.o: dulassociaterq.h dulassociaterq.cpp
	g++ -g -c dulassociaterq.cpp
dulassociateac.o: dulassociateac.h dulassociateac.cpp
	g++ -g -c dulassociateac.cpp
dulpdatatfrq.o: dulpdatatfrq.h dulpdatatfrq.cpp
	g++ -g -c dulpdatatfrq.cpp
dulcfindrsp.o: dulcfindrsp.h dulcfindrsp.cpp
	g++ -g -c dulcfindrsp.cpp
clean:
	rm *.o